# Generated by Django 4.2.2 on 2023-06-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_categoty_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedshop',
            name='receiver_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='connectedshop',
            name='sender_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='shop.shop'),
        ),
    ]
