# Generated by Django 4.2.2 on 2023-07-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_categoty_shop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quentity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
